/*Join and Having Clause*/
SELECT EMP_LNAME, EMP_FNAME, COUNT(*) AS SERVICE_COUNTS FROM WORKERS
INNER JOIN SERVICES ON SERVICE_EMP_ID = EMP_ID
GROUP BY EMP_LNAME, EMP_FNAME
HAVING SERVICE_COUNTS >= 2;

/*Join and Aggregate*/
SELECT INSTALLED_PART_ID, SUM(PART_PRICE) AS MACHINE_PART_COST 
FROM INSTALLED_PARTS
INNER JOIN PARTS ON PART_ID = INSTALLED_PART_ID 
GROUP BY INSTALLED_PART_ID
ORDER BY MACHINE_PART_COST DESC;

/*Creating Database View*/
CREATE VIEW Machine2Parts AS
	SELECT INSTALLED_PART_ID
	FROM INSTALLED_PARTS WHERE INSTALLED_MACHINE_ID = 2;