 /*Make the database*/
 CREATE DATABASE SPECANAL;
 
 /*MAKE WORKERS TABLE*/
CREATE TABLE WORKERS ( 
 EMP_ID 	INTEGER    NOT NULL UNIQUE auto_increment, 
 EMP_LNAME  VARCHAR(35) NOT NULL, 
 EMP_FNAME  VARCHAR(35) NOT NULL, 
 EMP_POSITION VARCHAR(80) NOT NULL,
 PRIMARY KEY (EMP_ID));
 
 /*MAKE CLIENTS TABLE*/
CREATE TABLE CLIENTS (
CLIENT_ID INTEGER NOT NULL UNIQUE auto_increment,
CLIENT_ASSIGNED_EMP_ID INTEGER NOT NULL,
CLIENT_ADDRESS VARCHAR(300) NOT NULL,
CLIENT_CONTACT_NAME VARCHAR(100) NOT NULL,
CLIENT_PHONE VARCHAR(25) NOT NULL,
CLIENT_MACHINE_ID INTEGER,
PRIMARY KEY (CLIENT_ID),
FOREIGN KEY (CLIENT_ASSIGNED_EMP_ID) REFERENCES WORKERS(EMP_ID)
);


/*MAKE SERVICES TABLE*/
CREATE TABLE SERVICES (
SERVICE_ID INTEGER NOT NULL UNIQUE auto_increment,
SERVICE_TYPE VARCHAR(500) NOT NULL,
SERVICE_EMP_ID INTEGER NOT NULL,
SERVICE_MACHINE_ID INTEGER NOT NULL,
SERVICE_DATE DATETIME NOT NULL,
SERVICE_CLIENT_ID INTEGER NOT NULL,
SERVICE_PART_ID INTEGER NOT NULL,
PRIMARY KEY(SERVICE_ID),
FOREIGN KEY(SERVICE_EMP_ID) REFERENCES WORKERS(EMP_ID),
FOREIGN KEY(SERVICE_CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);

/*MAKE MACHINES TABLE*/
CREATE TABLE MACHINES (
MACHINE_ID INTEGER NOT NULL UNIQUE auto_increment,
MACHINE_TYPE VARCHAR (100) NOT NULL,
MACHINE_CLIENT_ID INTEGER NOT NULL,
MACHINE_METAL_STANDARDS VARCHAR(1000) NOT NULL,
PRIMARY KEY(MACHINE_ID),
FOREIGN KEY(MACHINE_CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);

/*MAKE INSTALLED_PART TABLE*/
CREATE TABLE INSTALLED_PARTS (
INSTALLED_PART_ID INTEGER NOT NULL,
INSTALLED_MACHINE_ID INTEGER NOT NULL,
PRIMARY KEY(INSTALLED_PART_ID, INSTALLED_MACHINE_ID),
FOREIGN KEY(INSTALLED_MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

/*MAKE PARTS TABLE*/
CREATE TABLE PARTS (
PART_ID INTEGER NOT NULL UNIQUE AUTO_INCREMENT,
PART_STANDARDS VARCHAR(1000) NOT NULL,
PART_PRICE DECIMAL NOT NULL,
PRIMARY KEY (PART_ID)
);

/*MAKE FOEREIGN KEYS FOR TABLES THAT DID NOT EXIST BEFORE*/
ALTER TABLE CLIENTS ADD FOREIGN KEY (CLIENT_MACHINE_ID) REFERENCES MACHINES(MACHINE_ID);

ALTER TABLE SERVICES ADD FOREIGN KEY (SERVICE_MACHINE_ID) REFERENCES MACHINES(MACHINE_ID);

ALTER TABLE INSTALLED_PARTS ADD FOREIGN KEY(INSTALLED_PART_ID) REFERENCES PARTS(PART_ID);

/*WORKERS*/
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Polka','Alex','Manager');
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Welsh','Shawn','Field Mechanic');
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Lentz','Rick','Field Mechanic');
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Lanker','Peter','Field Mechanic');
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Ritcher','Kyle','Shop Manager');
INSERT INTO WORKERS(EMP_LNAME, EMP_FNAME, EMP_POSITION) VALUES('Campbell','Ryan','Shop Tech');

/*PARTS*/
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES ('Glass lens: Used for laser calibration.',351);
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES('Wire Casing', 50);
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES('Fuse box', 133);
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES('Main Board',2300);
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES('Standards Preset',4000);
INSERT INTO PARTS(PART_STANDARDS, PART_PRICE) VALUES('Optic Sensor',3400);

/*CLIENTS*/
INSERT INTO CLIENTS(CLIENT_ASSIGNED_EMP_ID, CLIENT_ADDRESS, CLIENT_CONTACT_NAME, CLIENT_PHONE, CLIENT_MACHINE_ID) VALUES(3,'1285 Walker Ln. Pittsburgh, PA','Paul','412-567-8978',NULL);
INSERT INTO CLIENTS(CLIENT_ASSIGNED_EMP_ID, CLIENT_ADDRESS, CLIENT_CONTACT_NAME, CLIENT_PHONE, CLIENT_MACHINE_ID) VALUES(3,'1738 Johnston Blvd. Olivander, CA','Tyler','515-302-5699',NULL);
INSERT INTO CLIENTS(CLIENT_ASSIGNED_EMP_ID, CLIENT_ADDRESS, CLIENT_CONTACT_NAME, CLIENT_PHONE, CLIENT_MACHINE_ID) VALUES(4,'18 Pen Island , DE','Richard','718-677-7943',NULL);
INSERT INTO CLIENTS(CLIENT_ASSIGNED_EMP_ID, CLIENT_ADDRESS, CLIENT_CONTACT_NAME, CLIENT_PHONE, CLIENT_MACHINE_ID) VALUES(4,'16 Rice Road Chicago, IL','Bob','145-768-9879',NULL);

/*MACHINES*/
INSERT INTO MACHINES(MACHINE_TYPE, MACHINE_CLIENT_ID, MACHINE_METAL_STANDARDS) VALUES('Handheld',1,'Low Alloy');
INSERT INTO MACHINES(MACHINE_TYPE, MACHINE_CLIENT_ID, MACHINE_METAL_STANDARDS) VALUES('Handheld',2,'Cast Iron');
INSERT INTO MACHINES(MACHINE_TYPE, MACHINE_CLIENT_ID, MACHINE_METAL_STANDARDS) VALUES('Handheld',3,'High Alloy');
INSERT INTO MACHINES(MACHINE_TYPE, MACHINE_CLIENT_ID, MACHINE_METAL_STANDARDS) VALUES('Handheld',4,'High Alloy');

/*INSTALLED_PARTS*/
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (1, 2);
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (2, 2);
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (3, 2);
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (4, 3);
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (3, 1);
INSERT INTO INSTALLED_PARTS (INSTALLED_PART_ID, INSTALLED_MACHINE_ID) VALUES (4, 2);

/*SERVICES*/
INSERT INTO SERVICES(SERVICE_TYPE, SERVICE_EMP_ID, SERVICE_MACHINE_ID, SERVICE_DATE, SERVICE_CLIENT_ID, SERVICE_PART_ID) VALUE('Lens Replacement',3,1,'2016-04-17',1,4);
INSERT INTO SERVICES(SERVICE_TYPE, SERVICE_EMP_ID, SERVICE_MACHINE_ID, SERVICE_DATE, SERVICE_CLIENT_ID, SERVICE_PART_ID) VALUE('Fuse Replace',3,2,'2017-05-15',2,2);
INSERT INTO SERVICES(SERVICE_TYPE, SERVICE_EMP_ID, SERVICE_MACHINE_ID, SERVICE_DATE, SERVICE_CLIENT_ID, SERVICE_PART_ID) VALUE('Board Replace',4,3,'2017-01-05',3,1);

/*UPDATE CLIENT TABLE TO ADD MACHINE_ID*/
UPDATE CLIENTS SET CLIENT_MACHINE_ID = 1 WHERE CLIENT_ID = 1;
UPDATE CLIENTS SET CLIENT_MACHINE_ID = 2 WHERE CLIENT_ID = 2;
UPDATE CLIENTS SET CLIENT_MACHINE_ID = 3 WHERE CLIENT_ID = 3;
UPDATE CLIENTS SET CLIENT_MACHINE_ID = 4 WHERE CLIENT_ID = 4;